alias add='git add -A'
alias commit='git commit -m "commit by alias" -m "this is used for short cut puspose"'
alias push='git push --all origin'
alias all='git add -A; git commit -m "commit by alias" -m "this is used for short cut puspose"; git push --all origin'
echo 'riyad'